version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: jade-whispers-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: bed
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jade_whispers
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - jade-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: jade-whispers-pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@jadewhispers.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped
    networks:
      - jade-network
    depends_on:
      - postgres

networks:
  jade-network:
    driver: bridge

volumes:
  postgres-data:
  pgadmin-data:
